{
 "title": "loki",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Service A Errors",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{app=\"service-a\", level=\"error\"} |= ``"
    }
   ]
  },
  {
   "title": "ServiceB Error",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "{app=\"service-b\", level=\"error\"} |= ``"
    }
   ]
  },
  {
   "title": "Service A Logs",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{app=\"service-a\"} |= ``"
    }
   ]
  },
  {
   "title": "Service B Logs",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "{app=\"service-b\"} |= ``"
    }
   ]
  }
 ]
}